### ISSUE TITLE
finatext は medium から zenn に移行したようです

### ISSUE THREAD

**Issue by YuseiUeno** [yamadashy/tech-blog-rss-feed#193]
https://github.com/yamadashy/tech-blog-rss-feed/blob/b4dc8c1ea0fd2a8ae9143d1a9d4b4b845918b93d/src/resources/feed-info-list.ts#L100

finatext は medium から zenn に移行したようです

https://techblog.finatext.com/%E3%83%86%E3%83%83%E3%82%AF%E3%83%96%E3%83%AD%E3%82%B0%E3%82%92zenn%E3%81%AB%E7%A7%BB%E8%A1%8C%E3%81%97%E3%81%BE%E3%81%97%E3%81%9F-70de7cedbdca

https://zenn.dev/p/finatext/feed

**Comment by yamadashy** [comment]
@YuseiUeno 
ご報告ありがとうございます！

大変助かります。

対応いたしました 🙇🏻
