### ISSUE TITLE
その企業の取り組みでないものが多く投稿される可能性があるブログ

### ISSUE THREAD

**Issue by YuseiUeno** [yamadashy/tech-blog-rss-feed#29]
その企業の取り組みでないものが多く投稿される可能性があるブログ に該当しそうですが、以下は追加しますか?

Findy Engineer Lab
https://findy-code.io/engineer-lab/archive
https://findy-code.io/engineer-lab/rss

**Comment by yamadashy** [comment]
気づくのが遅れてしまいました。申し訳ありません 🙇🏻 
ご提案ありがとうございます。

そちらのブログはすでに追加されているのですが、確認してみると確かに企業の取り組みではないものが多く投稿されいそうですね。
少し悩ましいですが、外すのを検討いたします。

**Comment by YuseiUeno** [comment]
実はリンク切れてました

https://github.com/yamadashy/tech-blog-rss-feed/blob/f122566282b151e390e8b35d69a3f3c9dd4307d8/src/resources/feed-info-list.ts#L75C2-L75C2
https://findy-code.io/engineer-lab/feed/atom

**Comment by yamadashy** [comment]
@YuseiUeno 
ありがとうございます。

リンク切れに気づかずすみません 🙇🏻 
リンクを正しいものに変更させていただきます。

消すかどうかに関しては、これは私の個人的な気持ちになるのですが、企業の取り組みでないものが投稿されていても、そこまで更新頻度も高くなくエンジニアリングについて良い情報を提供しているため、弊サイトのターゲットにとっては有益ではないかと判断し、掲載を続けることとします。

**Comment by yamadashy** [comment]
Findy Engineer Lab のブログに関しては、引き続き新しいURLをフィードさせていただく対応をいたしました。

もし、問題がなければこちらの issue を Close させていただきます。
ご連絡いただきありがとうございました 🙇🏻

**Comment by YuseiUeno** [comment]
承知しました
対応いただきありがとうございました :bow:

**Comment by yamadashy** [comment]
ありがとうございます :bow: またなにかございましたら、報告いただけると大変助かります。

ご報告いただきありがとうございました。
