### ISSUE TITLE
情報が取得できない（nput is not proper UTF-8, indicate encoding ）

### ISSUE THREAD

**Issue by philosophynote** [yamadashy/tech-blog-rss-feed#40]
お世話になっております。
SlackのRSSリーダーで情報を取得しております。
数日前から取得できない状況が続いており、
次のURLにアクセスしたところ、一番下のエラーが表示されておりました。

- https://yamadashy.github.io/tech-blog-rss-feed/feeds/atom.xml
- https://yamadashy.github.io/tech-blog-rss-feed/feeds/rss.xml

恐れ入りますが、ご確認をお願いいたします。

エラー内容

> This page contains the following errors:
> error on line 2101 at column 29: Input is not proper UTF-8, indicate encoding !
> Bytes: 0x0B 0xE6 0x8A 0xBD
> Below is a rendering of the page up to the first error.

**Comment by yamadashy** [comment]
@philosophynote 
申し訳ありません。返信が遅れてしまいました。
お世話になっております。

ご報告ありがとうございます 🙇🏻 
確認いたします。

**Comment by yamadashy** [comment]
とりいそぎ不正な文字列を含む記事があったため、一時的にブログを対象から外しました。
明日恒久対応いたします。このissueはその対応までOpenにします。

ご報告いただきありがとうございました。

**Comment by philosophynote** [comment]
ご多用のところご対応いただきありがとうございます。
恐れ入りますが引き続きよろしくお願いいたします。

**Comment by yamadashy** [comment]
こちらのPRにて修正が完了しましたので Close いたします 
https://github.com/yamadashy/tech-blog-rss-feed/pull/41

今回の件は全く気づいておらず、ご報告いただいて大変助かりました。
引き続きよろしくお願いいたします。
