### ISSUE TITLE
Generate Feedが完了しても、プロセスが終了せずに30分でタイムアウトすることがある

### ISSUE THREAD

**Issue by azu** [yamadashy/tech-blog-rss-feed#66]
ロジックは変更せずにForkして利用しています。

- [jser/watch-list-rss: JSer.infoの情報源を一つにまとめたRSSフィード](https://github.com/jser/watch-list-rss)

2-3日に一度程度Generate Feedが完了せずに30分でタイムアウトすることがあるようです。

```
[2024-01-19T12:15:12.030] [INFO] default - [create-feed] finished
[2024-01-19T12:15:12.064] [INFO] default - [FeedValidator] バリデーション開始
[2024-01-19T12:15:12.167] [INFO] default - [FeedValidator] バリデーション終了
[2024-01-19T12:15:12.167] [INFO] default - [FeedValidator] バリデーション開始
[2024-01-19T12:15:12.208] [INFO] default - [FeedValidator] バリデーション終了
[2024-01-19T12:15:12.683] [INFO] default - [store-feeds] finished
[2024-01-19T12:15:12.704] [INFO] default - [store-blog-feeds] finished
Error: The operation was canceled.
```

- 実際のエラーログ: https://github.com/jser/watch-list-rss/actions/runs/7583603251/job/20655585124#logs
- https://github.com/jser/watch-list-rss/actions?query=is%3Afailure

推測される原因として、何かしらの非同期処理が残ってることでNode.jsのEvent Loopが終了していないためプロセスが終了していないだと思います。

次のようなコードを実行すると、タイマーが完了するまでプロセスが終了しないようするためのNode.js側の仕組みがあります。(サーバ起動時など同じ)

```shell
$ cat a.js
setTimeout(()=>{}, 10_000);

$ time node a.js
node a.js  0.03s user 0.01s system 0% cpu 10.048 total
```
これと類似するタイマーや非同期処理が残ることで、GitHub Actions側の30分タイムアウトが発生していそうな気はします。イベントリスナーやタイマー、Promiseの処理などが何か残っている可能性がありそうです。

- [How does ExpressJS prevent NodeJS from exiting by itself? : r/node](https://www.reddit.com/r/node/comments/o0z1gx/how_does_expressjs_prevent_nodejs_from_exiting_by/)
- [Node.js — The Node.js Event Loop, Timers, and process.nextTick()](https://nodejs.org/en/guides/event-loop-timers-and-nexttick)

## ワークアラウンド

[process.exit([code])](https://nodejs.org/api/process.html#processexitcode)はイベントループに処理が残っていても強制的に終了することが可能なので、次の処理の最後に入れてしまうというのも解決方法としてありそうです。

https://github.com/yamadashy/tech-blog-rss-feed/blob/96f1eb203fd4203adbb42004b90253ce1b1cc8f0/src/feed/generate-feed-command.ts#L62-L73

## Note

こちらのリポジトリだとあまり発生していなさそう。
取得するサイトのエラーなどによる影響とかを受けてる可能性がありそう。
https://github.com/yamadashy/tech-blog-rss-feed/actions/runs/7181834600

**Comment by yamadashy** [comment]
@azu

**Comment by azu** [comment]
ありがとうございます。upstreamを取り込んでみます

**Comment by azu** [comment]
3日(24*3回)回していますが、特に再発はしてないので、解決しているような気がします。
対応ありがとうございました！

**Comment by yamadashy** [comment]
ありがとうございます！
色々とご教示いただき大変助かりました🙇‍♂️
